import {useEffect,useLayoutEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {BarChart3,Check,Clock3,History,Moon,Pause,Play,Settings as SettingsIcon,Square,Sun,TimerReset,Unlock,X} from 'lucide-react';
import {browserAlertPorts,notifyTimerTransition} from './lib/alerts';
import {syncBreakWindow} from './lib/break-window';
import {db} from './lib/storage';
import {applyTemplate,clearSelectedTemplateOnTimerChange} from './lib/template';
import {durationLabel,fmt,remaining,selectedFocusDuration,TimerSnapshot} from './lib/timer';
import type {Session,Settings,TimerState,Template} from './types';
import './styles.css';

const makeId=()=>crypto.randomUUID();
const initial=db.get();

export default function App(){
 const [page,setPage]=useState<'home'|'history'|'settings'>('home');
 const [settings,setSettings]=useState<Settings>(initial.settings);
 const [state,setState]=useState<TimerState>('IDLE');
 const [snap,setSnap]=useState<TimerSnapshot|null>(null);
 const [task,setTask]=useState('');
 const [left,setLeft]=useState(0);
 const [sessions,setSessions]=useState<Session[]>(initial.sessions);
 const [emergency,setEmergency]=useState(false);
 const [selectedTemplate,setSelectedTemplate]=useState<Template|null>(null);
 const [templates,setTemplates]=useState<Template[]>(initial.templates);
 const refresh=()=>setSessions(db.sessions());
 const saveSettings=(next:Settings)=>{setSettings(next);db.settings(next)};
 const chooseTemplate=(template:Template)=>{setSelectedTemplate(template);saveSettings({...settings,...applyTemplate(settings,template)})};
 const addTemplate=(template:Template)=>{const next=[...templates,template];setTemplates(next);db.saveTemplates(next);chooseTemplate(template)};
 const today=sessions.filter(s=>new Date(s.createdAt).toDateString()===new Date().toDateString());
 const focusSeconds=today.filter(s=>s.type==='focus').reduce((total,s)=>total+(s.actualDuration||0),0);
 const breakSeconds=today.filter(s=>s.type!=='focus').reduce((total,s)=>total+(s.actualDuration||0),0);
 const completedFocus=today.filter(s=>s.type==='focus'&&s.status==='completed').length;

 useEffect(()=>{document.documentElement.classList.toggle('dark',settings.theme==='dark'||(settings.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches));},[settings.theme]);
 useLayoutEffect(()=>{void syncBreakWindow(state==='BREAK',invoke).catch(console.error);},[state]);
 useEffect(()=>{if(!snap)return;const tick=()=>{const r=remaining(snap);setLeft(r);if(r<=0)finish()};tick();const id=window.setInterval(tick,250);return()=>clearInterval(id)},[snap,state]);
 useEffect(()=>{if(state==='BREAK'&&left<=0)finishBreak()},[left,state]);
 useEffect(()=>{if(settings.notificationsEnabled&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission()},[settings.notificationsEnabled]);
 useEffect(()=>{document.title=state==='BREAK'?`Break — ${fmt(left)}`:state==='FOCUS'||state==='FOCUS_PAUSED'?`Focus — ${fmt(left)}`:'Focus Balance'},[state,left]);

 function startFocus(){const duration=selectedTemplate?.focusDuration??settings.focusDuration;const now=Date.now();setSnap({startedAt:now,pausedAt:null,totalDuration:duration,accumulatedPausedTime:0});setLeft(duration);setState('FOCUS')}
 function pause(){if(!snap||state!=='FOCUS')return;setSnap({...snap,pausedAt:Date.now()});setState('FOCUS_PAUSED')}
 function resume(){if(!snap||state!=='FOCUS_PAUSED')return;setSnap({...snap,accumulatedPausedTime:snap.accumulatedPausedTime+(Date.now()-(snap.pausedAt||Date.now())),pausedAt:null});setState('FOCUS')}
 function stop(){if(state==='FOCUS'||state==='FOCUS_PAUSED'){const now=new Date().toISOString();db.saveSession({id:makeId(),type:'focus',status:'stopped',startedAt:new Date(snap?.startedAt||Date.now()).toISOString(),endedAt:now,plannedDuration:snap?.totalDuration||settings.focusDuration,actualDuration:Math.max(0,(snap?.totalDuration||settings.focusDuration)-left),task:task||undefined,createdAt:now});refresh()}setSnap(null);setState('IDLE');setLeft(0)}
 function finish(){if(state!=='FOCUS'||!snap)return;const now=new Date().toISOString();db.saveSession({id:makeId(),type:'focus',status:'completed',startedAt:new Date(snap.startedAt).toISOString(),endedAt:now,plannedDuration:snap.totalDuration,actualDuration:snap.totalDuration,task:task||undefined,templateId:selectedTemplate?.id,createdAt:now});refresh();const breakDur=selectedTemplate?.shortBreakDuration??settings.shortBreakDuration;const bNow=Date.now();setSnap({startedAt:bNow,pausedAt:null,totalDuration:breakDur,accumulatedPausedTime:0});setLeft(breakDur);setState('BREAK');notifyTimerTransition('break',settings,browserAlertPorts())}
 function finishBreak(){if(state!=='BREAK'||!snap)return;const now=new Date().toISOString();db.saveSession({id:makeId(),type:'short_break',status:'completed',startedAt:new Date(snap.startedAt).toISOString(),endedAt:now,plannedDuration:snap.totalDuration,actualDuration:snap.totalDuration,createdAt:now});refresh();notifyTimerTransition('focus',settings,browserAlertPorts());setSnap(null);setState(settings.autoStartFocus?'FOCUS':'IDLE');if(settings.autoStartFocus)startFocus()}
 function unlock(){setEmergency(false);if(state==='BREAK'&&snap){const now=new Date().toISOString();db.saveSession({id:makeId(),type:'short_break',status:'emergency_unlocked',startedAt:new Date(snap.startedAt).toISOString(),endedAt:now,plannedDuration:snap.totalDuration,actualDuration:snap.totalDuration-left,createdAt:now});refresh()}setSnap(null);setState('IDLE');setLeft(0)}

 if(state==='BREAK'||emergency)return <div className="break-screen"><div className="break-inner"><div className="eyebrow">REST</div><h1>TAKE A BREAK</h1><div className="break-time">{fmt(left)}</div><p>Step away from your screen.<br/>Rest your eyes. Stretch.</p><button className="danger-outline" onClick={()=>setEmergency(true)}><Unlock size={18}/> Emergency Unlock</button>{emergency&&<div className="modal"><div className="modal-card"><X className="modal-x" onClick={()=>setEmergency(false)}/><h2>Are you sure?</h2><p>Your break has {fmt(left)} remaining.<br/>This will interrupt your break.</p><div className="row"><button className="secondary" onClick={()=>setEmergency(false)}>Continue Break</button><button className="danger" onClick={unlock}>Unlock</button></div></div></div>}</div></div>;

 return <div className="app"><aside><div className="brand"><div className="brand-mark"><TimerReset size={19}/></div><span>Focus Balance</span></div><nav><button className={page==='home'?'active':''} onClick={()=>setPage('home')}><Clock3/>Focus</button><button className={page==='history'?'active':''} onClick={()=>setPage('history')}><History/>History</button><button className={page==='settings'?'active':''} onClick={()=>setPage('settings')}><SettingsIcon/>Settings</button></nav><div className="sidebar-foot"><div className="balance-mini"><span>Today's focus</span><b>{durationLabel(focusSeconds)}</b></div></div></aside><main>{page==='home'&&<Home state={state} left={left} task={task} setTask={setTask} start={startFocus} pause={pause} resume={resume} stop={stop} settings={settings} saveSettings={saveSettings} templates={templates} selected={selectedTemplate} select={chooseTemplate} addTemplate={addTemplate} clearTemplate={()=>setSelectedTemplate(clearSelectedTemplateOnTimerChange(selectedTemplate))} focusSeconds={focusSeconds} breakSeconds={breakSeconds} focusSessions={completedFocus}/>} {page==='history'&&<HistoryPage sessions={sessions}/>} {page==='settings'&&<SettingsPage settings={settings} setSettings={saveSettings}/>}</main></div>;
}

function Home(p:any){const [adding,setAdding]=useState(false);const update=(x:Partial<Settings>)=>{p.clearTemplate();p.saveSettings({...p.settings,...x})};const focusDuration=selectedFocusDuration(p.settings.focusDuration,p.selected?.focusDuration);return <div className="content focus-content"><header><div><div className="eyebrow">FOCUS & REST</div><h1>{p.state==='IDLE'?'Ready when you are.':p.state==='FOCUS_PAUSED'?'Focus paused.':'Deep work in progress.'}</h1><p>Build a sustainable rhythm between work and rest.</p></div><div className="header-stat"><BarChart3 size={17}/><span>Focus Balance</span></div></header><section className="timer-panel"><div className="state-pill"><span className={p.state==='FOCUS'?'dot pulse':'dot'}></span>{p.state==='IDLE'?'READY':p.state.replace('_',' ')}</div><div className="timer">{fmt(p.left||focusDuration)}</div>{p.state==='IDLE'?<><input className="task-input" placeholder="What are you focusing on? (optional)" value={p.task} onChange={e=>p.setTask(e.target.value)}/><div className="presets">{p.templates.map((template:Template)=><button className={p.selected?.id===template.id?'selected':''} key={template.id} onClick={()=>p.select(template)}>{template.name}</button>)}<button className="add-preset" onClick={()=>setAdding(true)}>+ Add preset</button></div><button className="primary big" onClick={p.start}><Play size={18} fill="currentColor"/> Start Focus</button></>:<div className="controls"><button className="secondary" onClick={p.state==='FOCUS_PAUSED'?p.resume:p.pause}>{p.state==='FOCUS_PAUSED'?<Play/>:<Pause/>}{p.state==='FOCUS_PAUSED'?'Resume':'Pause'}</button><button className="secondary" onClick={p.stop}><Square/> Stop</button></div>}</section><section className="timer-settings"><h2>Timer settings</h2><div className="timer-settings-grid"><Number label="Focus duration" value={p.settings.focusDuration/60} min={1} max={180} onChange={v=>update({focusDuration:v*60})}/><Number label="Short break" value={p.settings.shortBreakDuration/60} min={1} max={60} onChange={v=>update({shortBreakDuration:v*60})}/><Number label="Long break" value={p.settings.longBreakDuration/60} min={1} max={60} onChange={v=>update({longBreakDuration:v*60})}/><Number label="Sessions before long break" value={p.settings.sessionsBeforeLongBreak} min={1} max={12} onChange={v=>update({sessionsBeforeLongBreak:v})}/></div></section><section className="stats"><Stat label="Today's focus" value={durationLabel(p.focusSeconds)} sub="Completed focus time" icon={<Sun/>}/><Stat label="Focus sessions" value={String(p.focusSessions)} sub="Completed today" icon={<Check/>}/><Stat label="Work / rest" value={`${durationLabel(p.focusSeconds)} / ${durationLabel(p.breakSeconds)}`} sub="Focus / break today" icon={<Moon/>}/></section>{adding&&<PresetForm settings={p.settings} onCancel={()=>setAdding(false)} onSave={(template:Template)=>{p.addTemplate(template);setAdding(false)}}/>}</div>}
function PresetForm({settings,onCancel,onSave}:{settings:Settings;onCancel:()=>void;onSave:(template:Template)=>void}){const [name,setName]=useState('My preset');const [focus,setFocus]=useState(settings.focusDuration/60);const [shortBreak,setShortBreak]=useState(settings.shortBreakDuration/60);const [longBreak,setLongBreak]=useState(settings.longBreakDuration/60);const [sessions,setSessions]=useState(settings.sessionsBeforeLongBreak);return <div className="modal"><form className="modal-card preset-form" onSubmit={e=>{e.preventDefault();onSave({id:makeId(),name:name.trim()||'My preset',focusDuration:focus*60,shortBreakDuration:shortBreak*60,longBreakDuration:longBreak*60,sessionsBeforeLongBreak:sessions})}}><h2>Add preset</h2><label className="preset-name">Preset name<input autoFocus value={name} onChange={e=>setName(e.target.value)} maxLength={40}/></label><Number label="Focus duration" value={focus} min={1} max={180} onChange={setFocus}/><Number label="Short break" value={shortBreak} min={1} max={60} onChange={setShortBreak}/><Number label="Long break" value={longBreak} min={1} max={60} onChange={setLongBreak}/><Number label="Sessions before long break" value={sessions} min={1} max={12} onChange={setSessions}/><div className="row"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary" type="submit">Save preset</button></div></form></div>}
function Stat({label,value,sub,icon}:any){return <div className="stat"><div className="stat-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function HistoryPage({sessions}:any){return <div className="content"><header><div><div className="eyebrow">SESSION LOG</div><h1>History</h1><p>Your local focus and break sessions.</p></div></header><div className="list">{sessions.length===0?<div className="empty"><History size={30}/><h3>No sessions yet</h3><p>Completed sessions will appear here.</p></div>:sessions.map((s:Session)=><div className="history-row" key={s.id}><div className="history-icon">{s.type==='focus'?<Clock3/>:<Moon/>}</div><div><b>{s.type==='focus'?'Focus':s.type==='long_break'?'Long break':'Break'}</b><span>{new Date(s.startedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></div><strong>{Math.round((s.plannedDuration||0)/60)} min</strong><em className={s.status}>{s.status.replace('_',' ')}</em></div>)}</div></div>}
function SettingsPage({settings,setSettings}:{settings:Settings;setSettings:(s:Settings)=>void}){const update=(x:Partial<Settings>)=>setSettings({...settings,...x});return <div className="content narrow"><header><div><div className="eyebrow">PREFERENCES</div><h1>Settings</h1><p>Everything stays on this device.</p></div></header><div className="settings"><Setting title="Behavior"><Toggle label="Auto-start break" checked={settings.autoStartBreak} onChange={v=>update({autoStartBreak:v})}/><Toggle label="Auto-start focus" checked={settings.autoStartFocus} onChange={v=>update({autoStartFocus:v})}/></Setting><Setting title="Notifications"><Toggle label="Enable notifications" checked={settings.notificationsEnabled} onChange={v=>update({notificationsEnabled:v})}/><Toggle label="Enable sound" checked={settings.soundEnabled} onChange={v=>update({soundEnabled:v})}/></Setting><Setting title="Appearance"><div className="segmented">{(['system','light','dark'] as const).map(t=><button className={settings.theme===t?'selected':''} key={t} onClick={()=>update({theme:t})}>{t==='system'?'System':t==='light'?'Light':'Dark'}</button>)}</div></Setting></div></div>}
function Setting({title,children}:any){return <section className="setting"><h3>{title}</h3>{children}</section>}
function Number({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(value:number)=>void}){return <label className="setting-row"><span>{label}</span><input type="number" min={min} max={max} value={value} onChange={e=>onChange(Math.min(max,Math.max(min,+e.target.value)))}/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="setting-row"><span>{label}</span><input className="toggle" type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>}
